CREATE TABLE Address (
	id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
	country CHAR(15) NOT NULL,
	province CHAR(15) NOT NULL,
	city CHAR(15) NOT NULL,
	county CHAR(15) NOT NULL,
	street CHAR(15) NOT NULL,
	detail VARCHAR(255)
);
CREATE TABLE Account (
	id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
	execTime DATETIME NOT NULL,
	phone CHAR(11),
	mail CHAR(32),
	password CHAR(31) NOT NULL,
	alias CHAR(31) NOT NULL,
	portraitImagePath CHAR(63) NOT NULL,
	remainingSum FLOAT NOT NULL DEFAULT 0
);
CREATE TABLE AccountRank (
	id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
	rankLevel INTEGER NOT NULL,
	remainingDay INTEGER NOT NULL DEFAULT 0,
	Account_id INTEGER NOT NULL,
	CONSTRAINT AccountRank_Account_id_FK FOREIGN KEY (Account_id)
		REFERENCES Account(id)
		ON DELETE CASCADE
);
CREATE TABLE AccountAddress (
	id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
	Account_id INTEGER NOT NULL,
	Address_id INTEGER NOT NULL,
	CONSTRAINT AccountAddress_Account_id_FK FOREIGN KEY (Account_id)
		REFERENCES Account(id)
		ON DELETE CASCADE,
	CONSTRAINT AccountAddress_Address_id_FK FOREIGN KEY (Address_id)
		REFERENCES Address(id)
		ON DELETE CASCADE
);
CREATE TABLE RemainingSumHistory (
	id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
	execTime DATETIME NOT NULL,
	changeSum FLOAT NOT NULL,
	changeWay INTEGER NOT NULL,
	Account_id INTEGER NOT NULL,
	CONSTRAINT RemainingSumHistory_Account_id_FK FOREIGN KEY (Account_id)
		REFERENCES Account(id)
		ON DELETE CASCADE
);
CREATE TABLE Shop (
	id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
	execTime DATETIME NOT NULL,
	inBusiness BOOLEAN NOT NULL DEFAULT FALSE,
	name CHAR(31) NOT NULL,
	Address_id INTEGER NOT NULL DEFAULT -1,
	Account_id INTEGER NOT NULL,
	CONSTRAINT Shop_Address_id_FK FOREIGN KEY (Address_id)
		REFERENCES Address(id),
	CONSTRAINT Shop_Account_id_FK FOREIGN KEY (Account_id)
		REFERENCES Account(id)
		ON DELETE CASCADE
);
CREATE TABLE Coupon (
	id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
	priceSum FLOAT NOT NULL,
	worth FLOAT NOT NULL,
	remainingCount INTEGER NOT NULL DEFAULT 0,
	Shop_id INTEGER NOT NULL,
	CONSTRAINT Coupon_Shop_id_FK FOREIGN KEY (Shop_id)
		REFERENCES Shop(id)
		ON DELETE CASCADE
);
CREATE TABLE AccountCoupon (
	id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
	available BOOLEAN NOT NULL DEFAULT TRUE,
	priceSum FLOAT NOT NULL,
	worth FLOAT NOT NULL,
	Shop_id INTEGER NOT NULL,
	Account_id INTEGER NOT NULL,
	Coupon_id INTEGER NOT NULL,
	CONSTRAINT AccountCoupon_Shop_id_FK FOREIGN KEY (Shop_id)
		REFERENCES Shop(id)
		ON DELETE CASCADE,
	CONSTRAINT AccountCoupon_Account_id_FK FOREIGN KEY (Account_id)
		REFERENCES Account(id)
		ON DELETE CASCADE,
	CONSTRAINT AccountCoupon_Coupon_id_FK FOREIGN KEY (Coupon_id)
		REFERENCES Coupon(id)
);
CREATE TABLE Goods (
	id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
	execTime DATETIME NOT NULL,
	price FLOAT NOT NULL,
	discount FLOAT NOT NULL DEFAULT 1,
	name CHAR(127) NOT NULL,
	detail VARCHAR(255),
	remainingCount INTEGER NOT NULL DEFAULT 0,
	saleCount INTEGER NOT NULL DEFAULT 0,
	saleMonthCount INTEGER NOT NULL DEFAULT 0,
	Shop_id INTEGER NOT NULL,
	CONSTRAINT Goods_Shop_id_FK FOREIGN KEY (Shop_id)
		REFERENCES Shop(id)
		ON DELETE CASCADE
);
CREATE TABLE GoodsImage (
	id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
	imagePath CHAR(63) NOT NULL,
	Goods_id INTEGER NOT NULL,
	CONSTRAINT GoodsImage_Goods_id_FK FOREIGN KEY (Goods_id)
		REFERENCES Goods(id)
		ON DELETE CASCADE
);
CREATE TABLE GoodsInfo (
	id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
	imageFlag BOOLEAN NOT NULL DEFAULT FALSE,
	textInfo VARCHAR(255) NOT NULL,
	tailFlag BOOLEAN NOT NULL DEFAULT FALSE,
	Goods_id INTEGER NOT NULL,
	CONSTRAINT GoodsInfo_Goods_id_FK FOREIGN KEY (Goods_id)
		REFERENCES Goods(id)
		ON DELETE CASCADE
);
CREATE TABLE GoodsType (
	id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
	typeName CHAR(7) NOT NULL
);
CREATE TABLE GoodsLabel (
	id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
	Goods_id INTEGER NOT NULL,
	GoodsType_id INTEGER NOT NULL,
	CONSTRAINT GoodsLabel_Goods_id_FK FOREIGN KEY (Goods_id)
		REFERENCES Goods(id)
		ON DELETE CASCADE,
	CONSTRAINT GoodsLabel_GoodsType_id_FK FOREIGN KEY (GoodsType_id)
		REFERENCES GoodsType(id)
		ON UPDATE CASCADE ON DELETE CASCADE
);
CREATE TABLE TradeOrder (
	id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
	execTime DATETIME NOT NULL,
	status INTEGER NOT NULL DEFAULT 0,
	Shop_name CHAR(31) NOT NULL,
	address VARCHAR(255) NOT NULL,
	Account_id INTEGER NOT NULL,
	Shop_id INTEGER NOT NULL,
	CONSTRAINT TradeOrder_Account_id_FK FOREIGN KEY (Account_id)
		REFERENCES Account(id)
		ON DELETE CASCADE,
	CONSTRAINT TradeOrder_Shop_id_FK FOREIGN KEY (Shop_id)
		REFERENCES Shop(id)
);
CREATE TABLE TradeGoods (
	id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
	num INTEGER NOT NULL,
	Goods_name INTEGER NOT NULL,
	Goods_price FLOAT NOT NULL,
	Goods_id INTEGER NOT NULL,
	TradeOrder_id INTEGER NOT NULL,
	CONSTRAINT TradeGoods_Goods_id_FK FOREIGN KEY (Goods_id)
		REFERENCES Goods(id),
	CONSTRAINT TradeGoods_TradeOrder_id_FK FOREIGN KEY (TradeOrder_id)
		REFERENCES TradeOrder(id)
		ON DELETE CASCADE
);
CREATE TABLE ShopCollection (
	id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
	execTime DATETIME NOT NULL,
	Account_id INTEGER NOT NULL,
	Shop_id INTEGER NOT NULL,
	CONSTRAINT ShopCollection_Account_id_FK FOREIGN KEY (Account_id)
		REFERENCES Account(id)
		ON DELETE CASCADE,
	CONSTRAINT ShopCollection_Shop_id_FK FOREIGN KEY (Shop_id)
		REFERENCES Shop(id)
);
CREATE TABLE GoodsCollection (
	id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
	execTime DATETIME NOT NULL,
	Account_id INTEGER NOT NULL,
	Goods_id INTEGER NOT NULL DEFAULT,
	CONSTRAINT GoodsCollection_Account_id_FK FOREIGN KEY (Account_id)
		REFERENCES Account(id)
		ON DELETE CASCADE,
	CONSTRAINT GoodsCollection_Goods_id_FK FOREIGN KEY (Goods_id)
		REFERENCES Goods(id)
);
CREATE TABLE GoodsHistory (
	id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
	execTime DATETIME NOT NULL,
	Account_id INTEGER NOT NULL,
	Goods_id INTEGER NOT NULL,
	CONSTRAINT GoodsHistory_Account_id_FK FOREIGN KEY (Account_id)
		REFERENCES Account(id)
		ON DELETE CASCADE,
	CONSTRAINT GoodsHistory_Goods_id_FK FOREIGN KEY (Goods_id)
		REFERENCES Goods(id)
);
CREATE TABLE GoodsRemark (
	id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
	execTime DATETIME NOT NULL,
	content VARCHAR(255) NOT NULL,
	Goods_id INTEGER NOT NULL,
	Account_id INTEGER NOT NULL,
	CONSTRAINT GoodsRemark_Goods_id_FK FOREIGN KEY (Goods_id)
		REFERENCES Goods(id)
		ON DELETE CASCADE,
	CONSTRAINT GoodsRemark_Account_id_FK FOREIGN KEY (Account_id)
		REFERENCES Account(id)
);
CREATE TABLE GoodsDiscussion (
	id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
	execTime DATETIME NOT NULL,
	content VARCHAR(255) NOT NULL,
	Goods_id INTEGER NOT NULL,
	sender_Account_id INTEGER NOT NULL,
	receiver_Account_id INTEGER NOT NULL,
	CONSTRAINT GoodsDiscussion_Goods_id_FK FOREIGN KEY (Goods_id)
		REFERENCES Goods(id)
		ON DELETE CASCADE,
	CONSTRAINT GoodsDiscussion_sender_Account_id_FK FOREIGN KEY (sender_Account_id)
		REFERENCES Account(id),
	CONSTRAINT GoodsDiscussion_receiver_Account_id_FK FOREIGN KEY (receiver_Account_id)
		REFERENCES Account(id)
);
CREATE TABLE MessageGoodsDiscussion (
	id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
	Account_id INTEGER NOT NULL,
	GoodsDiscussion_id INTEGER NOT NULL,
	unread BOOLEAN NOT NULL DEFAULT TRUE,
	CONSTRAINT MessageGoodsDiscussion_Account_id_FK FOREIGN KEY (Account_id)
		REFERENCES Account(id)
		ON DELETE CASCADE,
	CONSTRAINT MessageGoodsDiscussion_GoodsDiscussion_id_FK FOREIGN KEY (GoodsDiscussion_id)
		REFERENCES GoodsDiscussion(id)
		ON DELETE CASCADE
);
CREATE TABLE MessageTradeOrder (
	id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
	Account_id INTEGER NOT NULL,
	TradeOrder_id INTEGER NOT NULL,
	unread BOOLEAN NOT NULL DEFAULT TRUE,
	CONSTRAINT MessageTradeOrder_Account_id_FK FOREIGN KEY (Account_id)
		REFERENCES Account(id)
		ON DELETE CASCADE,
	CONSTRAINT MessageTradeOrder_TradeOrder_id_FK FOREIGN KEY (TradeOrder_id)
		REFERENCES TradeOrder(id)
		ON DELETE CASCADE
);
CREATE TABLE MessageTradeOrderCancel (
	id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
	detail VARCHAR(255),
	TradeOrder_id INTEGER NOT NULL,
	unread BOOLEAN NOT NULL DEFAULT TRUE,
	CONSTRAINT MessageTradeOrderCancel_TradeOrder_id_FK FOREIGN KEY (TradeOrder_id)
		REFERENCES TradeOrder(id)
		ON DELETE CASCADE
);
